### ISSUE TITLE
Players reset to level 1 after updating?

### ISSUE THREAD

**Issue by thatgraemeguy** [cornernote/minetest-skyblock#24]
So I started a new server yesterday, cloned the github repo. After updating the mod this morning I've noticed that 2 people have complained that they were half way through level 2 when they left and now have been reset to level 1.

Is that normal?

I can't test on my player, I died last night and then left the game, so I was already reset to level 1 before updating the mod this morning.

**Comment by cornernote** [comment]
I made improvements on the way the feats are stored. Instead of putting
everyone's feats in one huge file it now writes a file per player.  This
will greatly reduce disk io when there are a lot of players. In addition
the file format changed. Unfortunately the downside is that all existing
feats are lost.

The mod is still in development so although I will try to avoid breaking
changes like this, there may be more leading up to the 1.0 release.

**Comment by thatgraemeguy** [comment]
OK, thanks
