### ISSUE TITLE
"Place a sign" quest is not recognised when signs_lib mod is enabled

### ISSUE THREAD

**Issue by thatgraemeguy** [cornernote/minetest-skyblock#44]
When signs_lib from VanessaE's homedecor_modpack is enabled, the level 1 quest "place a sign" doesn't seem to trigger. The itemstring is still "default:sign_wall", so I'm not sure why it doesn't work.

**Comment by thatgraemeguy** [comment]
https://github.com/VanessaE/homedecor_modpack/blob/master/signs_lib/init.lua

**Comment by LeMagnesium** [comment]
This problem originates from `signs_lib` itself. Signs are overriden and when their on_place callback [is called](https://github.com/VanessaE/homedecor_modpack/blob/master/signs_lib/init.lua#L634), it always returns an itemstack, which prevents any other `on_place` callback to be called, included those declared in feats. The only solution is to modificate signs_lib itself.

**Comment by cornernote** [comment]
@LeMagnesium, so adding it to this list doesnt help:
https://github.com/cornernote/minetest-skyblock/blob/master/skyblock_levels/skyblock.feats.lua#L205
?

**Comment by LeMagnesium** [comment]
No, I don't think it helps, because [this](https://github.com/cornernote/minetest-skyblock/blob/master/skyblock_levels/skyblock.feats.lua#L183) is never called when one of the signs overriden by signs_lib is placed, no on_place callback is called, not even the ones which logs node placement. This is probably the most painful flaw I've seen in Minetest's API : blocked callbacks.

**Comment by cornernote** [comment]
I just tested it and it seems to work.  I'll push the change.  Let me know if it works for you.

**Comment by LeMagnesium** [comment]
I studied it a bit more, and redefining again the item is the only way to solve that. Great fix.
